# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsware', '0002_auto_20170425_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
