# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whatsware', '0003_auto_20170424_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
