# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsware', '0004_event_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
