# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsware', '0005_auto_20170425_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
